route:
  group_by: [alertname, datacenter, app]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'gotify-notifications'
receivers:
- name: 'gotify-notifications'
  webhook_configs:
    - url: 'http://192.168.22.15:8435/'