
global:
  scrape_interval: 15s
  evaluation_interval: 2s

rule_files:
- ./alert_rules.yml  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['192.168.22.11:9000']

  - job_name: minio-job-bucket
    metrics_path: /minio/v2/metrics/bucket
    scheme: http
    static_configs:
    - targets: ['192.168.22.11:9000']

  - job_name: minio-job-node
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
    - targets: ['192.168.226.22.11:9000']

  - job_name: minio-job-resource
    metrics_path: /minio/v2/metrics/resource
    scheme: http
    static_configs:
    - targets: ['192.168.22.11:9000']
  
alerting:
 alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['192.168.22.14:9093']